# Change these first
owner: RandomStudio # Your GitHub organization or username, where this repository lives
repo: randomstudio-upptime # The name of this repository

sites:
  - name: Random Studio
    url: https://random.studio
  - name: Random Studio (www)
    url: https://random.studio
  - name: Random Studio (http)
    url: http://random.studio
  - name: Test bad site
    url: http://random.studiof

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.random.studio
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Random Studio uptime status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
